var hierarchy =
[
    [ "proto::lacte::ActivationTime", "da/d99/structproto_1_1lacte_1_1ActivationTime.html", null ],
    [ "proto::lacte::BoardErrorDiff", "db/db3/classproto_1_1lacte_1_1BoardErrorDiff.html", null ],
    [ "proto::lacte::BoardPacket< BASE >", "dc/d65/structproto_1_1lacte_1_1BoardPacket.html", null ],
    [ "proto::lacte::BootAnswerType", "d3/d27/structproto_1_1lacte_1_1BootAnswerType.html", null ],
    [ "CustomSpan< T >", "d6/d58/classCustomSpan.html", null ],
    [ "proto::lacte::DrinkCounter", "d9/d59/structproto_1_1lacte_1_1DrinkCounter.html", null ],
    [ "proto::EmptyDataType", "d3/d7a/structproto_1_1EmptyDataType.html", null ],
    [ "proto::lacte::ErrorFlags", "d9/db4/classproto_1_1lacte_1_1ErrorFlags.html", null ],
    [ "proto::exoAtlant::exoAtlantPacket< BASE >", "d3/d58/structproto_1_1exoAtlant_1_1exoAtlantPacket.html", null ],
    [ "std::false_type", null, [
      [ "proto::FieldPrototype< NAME_, TYPE_, BASE_, FLAGS_, MAX_SIZE, SIZE, CONST_VALUE_, MATCHER >::IsStdVector< class >", "db/d28/structproto_1_1FieldPrototype_1_1IsStdVector.html", null ],
      [ "proto::IsDataFieldPrototype< T, typename >", "da/da9/structproto_1_1IsDataFieldPrototype.html", null ],
      [ "proto::meta::tl_contains< TypeList<>, T >", "db/d95/structproto_1_1meta_1_1tl__contains_3_01TypeList_3_4_00_01T_01_4.html", null ]
    ] ],
    [ "proto::FieldByNameImpl< Tuple, NAME, Index, AtEnd >", "dd/de3/structproto_1_1FieldByNameImpl.html", null ],
    [ "proto::FieldByNameImpl< Tuple, NAME, Index, false >", "df/def/structproto_1_1FieldByNameImpl_3_01Tuple_00_01NAME_00_01Index_00_01false_01_4.html", null ],
    [ "proto::FieldByNameImpl< Tuple, NAME, Index, true >", "d8/d95/structproto_1_1FieldByNameImpl_3_01Tuple_00_01NAME_00_01Index_00_01true_01_4.html", null ],
    [ "proto::FieldContainer< Fields, TCrc >", "d5/d09/classproto_1_1FieldContainer.html", [
      [ "proto::RxContainer< exoAtlantPacket< RX_BASE >::packet_fields, custom_crc >", "d0/d29/classproto_1_1RxContainer.html", null ],
      [ "proto::RxContainer< HostPacket< RX_BASE >::packet_fields, Crc16Modbus >", "d0/d29/classproto_1_1RxContainer.html", null ],
      [ "proto::RxContainer< BoardPacket< RX_BASE >::packet_fields, Crc16Modbus >", "d0/d29/classproto_1_1RxContainer.html", null ],
      [ "proto::RxContainer< RxFields, CrcSoft >", "d0/d29/classproto_1_1RxContainer.html", null ],
      [ "proto::TxContainer< exoAtlantPacket< TX_BASE >::packet_fields, custom_crc >", "d4/dd2/classproto_1_1TxContainer.html", null ],
      [ "proto::TxContainer< BoardPacket< TX_BASE >::packet_fields, Crc16Modbus >", "d4/dd2/classproto_1_1TxContainer.html", null ],
      [ "proto::TxContainer< HostPacket< TX_BASE >::packet_fields, Crc16Modbus >", "d4/dd2/classproto_1_1TxContainer.html", null ],
      [ "proto::TxContainer< TxFields, CrcSoft >", "d4/dd2/classproto_1_1TxContainer.html", null ],
      [ "proto::RxContainer< Fields, TCrc >", "d0/d29/classproto_1_1RxContainer.html", null ],
      [ "proto::TxContainer< Fields, TCrc >", "d4/dd2/classproto_1_1TxContainer.html", null ]
    ] ],
    [ "proto::FieldContainer< BoardPacket< RX_BASE >::packet_fields, Crc16Modbus >", "d5/d09/classproto_1_1FieldContainer.html", null ],
    [ "proto::FieldContainer< BoardPacket< TX_BASE >::packet_fields, Crc16Modbus >", "d5/d09/classproto_1_1FieldContainer.html", null ],
    [ "proto::FieldContainer< exoAtlantPacket< RX_BASE >::packet_fields, custom_crc >", "d5/d09/classproto_1_1FieldContainer.html", null ],
    [ "proto::FieldContainer< exoAtlantPacket< TX_BASE >::packet_fields, custom_crc >", "d5/d09/classproto_1_1FieldContainer.html", null ],
    [ "proto::FieldContainer< Fields, CrcSoft >", "d5/d09/classproto_1_1FieldContainer.html", null ],
    [ "proto::FieldContainer< HostPacket< RX_BASE >::packet_fields, Crc16Modbus >", "d5/d09/classproto_1_1FieldContainer.html", null ],
    [ "proto::FieldContainer< HostPacket< TX_BASE >::packet_fields, Crc16Modbus >", "d5/d09/classproto_1_1FieldContainer.html", null ],
    [ "proto::FieldContainer< RxFields, CrcSoft >", "d5/d09/classproto_1_1FieldContainer.html", null ],
    [ "proto::FieldContainer< TxFields, CrcSoft >", "d5/d09/classproto_1_1FieldContainer.html", null ],
    [ "FieldEndpoint< RX_FIELDS, TX_FIELDS >", "dc/dee/classFieldEndpoint.html", null ],
    [ "proto::FieldInfo< N, T >", "d3/d48/structproto_1_1FieldInfo.html", null ],
    [ "proto::FieldPrototype< NAME_, TYPE_, BASE_, FLAGS_, MAX_SIZE, SIZE, CONST_VALUE_, MATCHER >", "dc/d80/classproto_1_1FieldPrototype.html", [
      [ "proto::DataFieldPrototype< PACKETS, BASE, FLAGS, MAX_SIZE >", "d3/dc2/classproto_1_1DataFieldPrototype.html", null ]
    ] ],
    [ "proto::FieldPrototype< FieldName::DATA_FIELD, uint8_t *, BASE, FLAGS, 4096 >", "dc/d80/classproto_1_1FieldPrototype.html", null ],
    [ "proto::fieldsTuple< Field >", "de/dc7/structproto_1_1fieldsTuple.html", null ],
    [ "proto::fieldsTuple< DataFieldPrototype< PACKETS, BASE, FLAGS, MAX_SIZE > >", "d4/d5a/structproto_1_1fieldsTuple_3_01DataFieldPrototype_3_01PACKETS_00_01BASE_00_01FLAGS_00_01MAX__SIZE_01_4_01_4.html", null ],
    [ "proto::fieldsTuple< proto::FieldPrototype< NAME, T, BASE, FLAGS, MAX_SIZE, SIZE, CONST_VALUE, MATCHER > >", "d9/dcd/structproto_1_1fieldsTuple_3_01proto_1_1FieldPrototype_3_01NAME_00_01T_00_01BASE_00_01FLAGS_00_00018c80385ad869322e2c0331e25f8f1.html", null ],
    [ "proto::FieldTraits< Field >", "da/dd9/structproto_1_1FieldTraits.html", null ],
    [ "proto::lacte::HostPacket< BASE >", "d0/ded/structproto_1_1lacte_1_1HostPacket.html", null ],
    [ "ICrc", "d7/d70/classICrc.html", [
      [ "proto::exoAtlant::custom_crc", "d3/d8e/classproto_1_1exoAtlant_1_1custom__crc.html", null ]
    ] ],
    [ "proto::interface::IInterface", "d8/d57/classproto_1_1interface_1_1IInterface.html", null ],
    [ "proto::lacte::InfoPacketType", "da/d22/structproto_1_1lacte_1_1InfoPacketType.html", null ],
    [ "std::integral_constant", null, [
      [ "proto::meta::tl_index_of< TypeList< T, Ts... >, T >", "d1/d28/structproto_1_1meta_1_1tl__index__of_3_01TypeList_3_01T_00_01Ts_8_8_8_01_4_00_01T_01_4.html", null ],
      [ "proto::meta::tl_index_of< TypeList< U, Ts... >, T >", "d7/d30/structproto_1_1meta_1_1tl__index__of_3_01TypeList_3_01U_00_01Ts_8_8_8_01_4_00_01T_01_4.html", null ]
    ] ],
    [ "proto::lacte::LacteId", "d3/dec/structproto_1_1lacte_1_1LacteId.html", null ],
    [ "proto::lacte::LacteSn", "db/daa/structproto_1_1lacte_1_1LacteSn.html", null ],
    [ "proto::lacte::MachineSn", "d7/d46/structproto_1_1lacte_1_1MachineSn.html", null ],
    [ "proto::lacte::MagicWord", "d6/dbf/structproto_1_1lacte_1_1MagicWord.html", null ],
    [ "proto::FieldContainer< Fields, TCrc >::MakeNamedValueTuple< Tuple >", "db/d4f/structproto_1_1FieldContainer_1_1MakeNamedValueTuple.html", null ],
    [ "proto::FieldContainer< Fields, TCrc >::MakeNamedValueTuple< std::tuple< Field... > >", "d4/dd9/structproto_1_1FieldContainer_1_1MakeNamedValueTuple_3_01std_1_1tuple_3_01Field_8_8_8_01_4_01_4.html", null ],
    [ "proto::FieldContainer< Fields, TCrc >::MakeReturnTuple< Tuple_ >", "d0/db1/structproto_1_1FieldContainer_1_1MakeReturnTuple.html", null ],
    [ "proto::FieldContainer< Fields, TCrc >::MakeReturnTuple< std::tuple< Field... > >", "df/db0/structproto_1_1FieldContainer_1_1MakeReturnTuple_3_01std_1_1tuple_3_01Field_8_8_8_01_4_01_4.html", null ],
    [ "proto::FieldContainer< Fields, TCrc >::MakeValueTuple< Tuple >", "d8/dc9/structproto_1_1FieldContainer_1_1MakeValueTuple.html", null ],
    [ "proto::FieldContainer< Fields, TCrc >::MakeValueTuple< std::tuple< Field... > >", "d4/dac/structproto_1_1FieldContainer_1_1MakeValueTuple_3_01std_1_1tuple_3_01Field_8_8_8_01_4_01_4.html", null ],
    [ "proto::lacte::McuUid", "de/d3d/structproto_1_1lacte_1_1McuUid.html", null ],
    [ "proto::FieldContainer< Fields, TCrc >::NamedCopyType< NAME_, T_ >", "de/d72/structproto_1_1FieldContainer_1_1NamedCopyType.html", null ],
    [ "proto::FieldContainer< Fields, TCrc >::NamedValue< NAME_, T_ >", "d4/dfa/structproto_1_1FieldContainer_1_1NamedValue.html", null ],
    [ "proto::exoAtlant::Packet1", "da/db7/structproto_1_1exoAtlant_1_1Packet1.html", null ],
    [ "proto::exoAtlant::Packet2", "df/da0/structproto_1_1exoAtlant_1_1Packet2.html", null ],
    [ "proto::exoAtlant::Packet3", "d9/db4/structproto_1_1exoAtlant_1_1Packet3.html", null ],
    [ "proto::PacketInfo< Id, PacketType >", "dc/dee/structproto_1_1PacketInfo.html", null ],
    [ "proto::meta::packets_to_typelist< PACKETS >", "d7/d41/structproto_1_1meta_1_1packets__to__typelist.html", null ],
    [ "proto::meta::packets_to_typelist< std::tuple< Pairs... > >", "dd/d70/structproto_1_1meta_1_1packets__to__typelist_3_01std_1_1tuple_3_01Pairs_8_8_8_01_4_01_4.html", null ],
    [ "proto::exoAtlant::pkt_desc_t", "df/d26/structproto_1_1exoAtlant_1_1pkt__desc__t.html", null ],
    [ "proto::lacte::ProdDate", "dc/d74/structproto_1_1lacte_1_1ProdDate.html", null ],
    [ "proto::lacte::ProductShelfLife", "d1/df0/structproto_1_1lacte_1_1ProductShelfLife.html", null ],
    [ "proto::lacte::ProductVolume", "d2/da1/structproto_1_1lacte_1_1ProductVolume.html", null ],
    [ "proto::ProtocolEndpoint< RxFields, TxFields, Crc >", "d6/dc5/classproto_1_1ProtocolEndpoint.html", null ],
    [ "proto::ProtocolEndpoint< BoardPacket< RX_BASE >::packet_fields, HostPacket< TX_BASE >::packet_fields, Crc16Modbus >", "d6/dc5/classproto_1_1ProtocolEndpoint.html", [
      [ "proto::lacte::LacteHostProtocol< RX_BASE, TX_BASE >", "d3/db5/classproto_1_1lacte_1_1LacteHostProtocol.html", null ]
    ] ],
    [ "proto::ProtocolEndpoint< HostPacket< RX_BASE >::packet_fields, BoardPacket< TX_BASE >::packet_fields, Crc16Modbus >", "d6/dc5/classproto_1_1ProtocolEndpoint.html", [
      [ "proto::lacte::LacteBoardProtocol< RX_BASE, TX_BASE >", "db/d30/classproto_1_1lacte_1_1LacteBoardProtocol.html", null ]
    ] ],
    [ "proto::ProtocolNoSysEndpoint< RxFields, TxFields, Crc >", "d3/d19/classproto_1_1ProtocolNoSysEndpoint.html", null ],
    [ "proto::ProtocolNoSysEndpoint< exoAtlantPacket< RX_BASE >::packet_fields, exoAtlantPacket< TX_BASE >::packet_fields, custom_crc >", "d3/d19/classproto_1_1ProtocolNoSysEndpoint.html", [
      [ "proto::exoAtlant::ExoAtlantProtocol_< RX_BASE, TX_BASE >", "d4/d66/classproto_1_1exoAtlant_1_1ExoAtlantProtocol__.html", null ]
    ] ],
    [ "proto::FieldContainer< Fields, TCrc >::PtrToVec< T >", "d0/de9/structproto_1_1FieldContainer_1_1PtrToVec.html", null ],
    [ "proto::FieldContainer< Fields, TCrc >::PtrToVec< const U * >", "de/d4b/structproto_1_1FieldContainer_1_1PtrToVec_3_01const_01U_01_5_01_4.html", null ],
    [ "proto::FieldContainer< Fields, TCrc >::PtrToVec< U * >", "d9/d93/structproto_1_1FieldContainer_1_1PtrToVec_3_01U_01_5_01_4.html", null ],
    [ "proto::meta::PtrToVector< T >", "da/dce/structproto_1_1meta_1_1PtrToVector.html", null ],
    [ "proto::meta::PtrToVector< U * >", "d0/d6b/structproto_1_1meta_1_1PtrToVector_3_01U_01_5_01_4.html", null ],
    [ "proto::lacte::RFIDDataPacketType", "d3/d09/structproto_1_1lacte_1_1RFIDDataPacketType.html", null ],
    [ "proto::lacte::RFIDNumberType", "df/dc6/structproto_1_1lacte_1_1RFIDNumberType.html", null ],
    [ "proto::FieldContainer< Fields, TCrc >::StripConstFromVector< T >", "d8/d3e/structproto_1_1FieldContainer_1_1StripConstFromVector.html", null ],
    [ "proto::FieldContainer< Fields, TCrc >::StripConstFromVector< std::vector< U, Alloc > >", "d3/d9f/structproto_1_1FieldContainer_1_1StripConstFromVector_3_01std_1_1vector_3_01U_00_01Alloc_01_4_01_4.html", null ],
    [ "proto::lacte::TimeCounter", "df/dbe/structproto_1_1lacte_1_1TimeCounter.html", null ],
    [ "proto::meta::tl_contains< List, T >", "d1/d34/structproto_1_1meta_1_1tl__contains.html", null ],
    [ "proto::meta::tl_contains< TypeList< Ts... >, T >", "d1/d34/structproto_1_1meta_1_1tl__contains.html", [
      [ "proto::meta::tl_contains< TypeList< U, Ts... >, T >", "dd/db3/structproto_1_1meta_1_1tl__contains_3_01TypeList_3_01U_00_01Ts_8_8_8_01_4_00_01T_01_4.html", null ]
    ] ],
    [ "proto::meta::tl_index_of< List, T >", "dc/d00/structproto_1_1meta_1_1tl__index__of.html", null ],
    [ "proto::meta::tl_index_of< TypeList<>, T >", "da/d33/structproto_1_1meta_1_1tl__index__of_3_01TypeList_3_4_00_01T_01_4.html", null ],
    [ "proto::meta::tl_push_back< List, T >", "d9/d2f/structproto_1_1meta_1_1tl__push__back.html", null ],
    [ "proto::meta::tl_push_back< TypeList< Ts... >, T >", "d4/d8b/structproto_1_1meta_1_1tl__push__back_3_01TypeList_3_01Ts_8_8_8_01_4_00_01T_01_4.html", null ],
    [ "proto::meta::tl_to_variant< List >", "d9/d9c/structproto_1_1meta_1_1tl__to__variant.html", null ],
    [ "proto::meta::tl_to_variant< TypeList< Ts... > >", "db/d7c/structproto_1_1meta_1_1tl__to__variant_3_01TypeList_3_01Ts_8_8_8_01_4_01_4.html", null ],
    [ "proto::meta::tl_unique< List >", "d4/d9d/structproto_1_1meta_1_1tl__unique.html", null ],
    [ "proto::meta::tl_unique< TypeList< T, Ts... > >", "d6/dd3/structproto_1_1meta_1_1tl__unique_3_01TypeList_3_01T_00_01Ts_8_8_8_01_4_01_4.html", null ],
    [ "proto::meta::tl_unique< TypeList<> >", "dd/d90/structproto_1_1meta_1_1tl__unique_3_01TypeList_3_4_01_4.html", null ],
    [ "proto::TransformToFieldsTuple< Tuple >", "d6/df7/structproto_1_1TransformToFieldsTuple.html", null ],
    [ "proto::TransformToFieldsTuple< BoardPacket< RX_BASE >::packet_fields >", "d6/df7/structproto_1_1TransformToFieldsTuple.html", null ],
    [ "proto::TransformToFieldsTuple< BoardPacket< TX_BASE >::packet_fields >", "d6/df7/structproto_1_1TransformToFieldsTuple.html", null ],
    [ "proto::TransformToFieldsTuple< exoAtlantPacket< RX_BASE >::packet_fields >", "d6/df7/structproto_1_1TransformToFieldsTuple.html", null ],
    [ "proto::TransformToFieldsTuple< exoAtlantPacket< TX_BASE >::packet_fields >", "d6/df7/structproto_1_1TransformToFieldsTuple.html", null ],
    [ "proto::TransformToFieldsTuple< Fields >", "d6/df7/structproto_1_1TransformToFieldsTuple.html", null ],
    [ "proto::TransformToFieldsTuple< HostPacket< RX_BASE >::packet_fields >", "d6/df7/structproto_1_1TransformToFieldsTuple.html", null ],
    [ "proto::TransformToFieldsTuple< HostPacket< TX_BASE >::packet_fields >", "d6/df7/structproto_1_1TransformToFieldsTuple.html", null ],
    [ "proto::TransformToFieldsTuple< RxFields >", "d6/df7/structproto_1_1TransformToFieldsTuple.html", null ],
    [ "proto::TransformToFieldsTuple< std::tuple< Fields... > >", "db/d45/structproto_1_1TransformToFieldsTuple_3_01std_1_1tuple_3_01Fields_8_8_8_01_4_01_4.html", null ],
    [ "proto::TransformToFieldsTuple< TxFields >", "d6/df7/structproto_1_1TransformToFieldsTuple.html", null ],
    [ "std::true_type", null, [
      [ "proto::FieldPrototype< NAME_, TYPE_, BASE_, FLAGS_, MAX_SIZE, SIZE, CONST_VALUE_, MATCHER >::IsStdVector< std::vector< U, A > >", "d6/d3f/structproto_1_1FieldPrototype_1_1IsStdVector_3_01std_1_1vector_3_01U_00_01A_01_4_01_4.html", null ],
      [ "proto::IsDataFieldPrototype< T, std::void_t< decltype(std::remove_cv_t< std::remove_reference_t< T > >::IS_DATA_FIELD)> >", "d6/d4f/structproto_1_1IsDataFieldPrototype_3_01T_00_01std_1_1void__t_3_01decltype_07std_1_1remove__cv__6f0f04b2e30fbb93b5e802d2373c777f.html", null ],
      [ "proto::meta::tl_contains< TypeList< T, Ts... >, T >", "da/d65/structproto_1_1meta_1_1tl__contains_3_01TypeList_3_01T_00_01Ts_8_8_8_01_4_00_01T_01_4.html", null ]
    ] ],
    [ "proto::meta::TypeList< Ts >", "dd/d65/structproto_1_1meta_1_1TypeList.html", null ],
    [ "proto::lacte::UIDPacketType", "dd/dda/structproto_1_1lacte_1_1UIDPacketType.html", null ],
    [ "proto::meta::UniqueVariant< PACKETS >", "db/d6c/structproto_1_1meta_1_1UniqueVariant.html", null ],
    [ "proto::lacte::UsageTime", "d9/d77/structproto_1_1lacte_1_1UsageTime.html", null ],
    [ "proto::lacte::VersionPacketType::Version", "da/da7/structproto_1_1lacte_1_1VersionPacketType_1_1Version.html", null ],
    [ "proto::lacte::VersionPacketType", "d7/d99/structproto_1_1lacte_1_1VersionPacketType.html", null ],
    [ "proto::lacte::VirtualBoard< RX_BASE, TX_BASE >", "d3/d67/classproto_1_1lacte_1_1VirtualBoard.html", null ],
    [ "YmodemPrerelease", "de/d8f/classYmodemPrerelease.html", null ]
];